"""modulo 2: tabla revisiones_estrategicas (paginas 2 y 3)

Revision ID: 7410d0be66bf
Revises: 632bc9333223
Create Date: 2026-07-15 22:02:27.074067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7410d0be66bf'
down_revision: Union[str, None] = '632bc9333223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisiones_estrategicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('objetivo_estrategico', sa.Text(), nullable=False),
    sa.Column('ejes_estrategicos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('beneficios_esperados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisiones_estrategicas_familia_id'), 'revisiones_estrategicas', ['familia_id'], unique=True)
    op.create_index(op.f('ix_revisiones_estrategicas_id'), 'revisiones_estrategicas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisiones_estrategicas_id'), table_name='revisiones_estrategicas')
    op.drop_index(op.f('ix_revisiones_estrategicas_familia_id'), table_name='revisiones_estrategicas')
    op.drop_table('revisiones_estrategicas')
    # ### end Alembic commands ###
